name: OWASP ZAP Integration with GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      
      - name: Start OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://testphp.vulnweb.com/'
          cmd_options: '-config api.disablekey=true'
          fail_on_warning: true

        
          name: zap-report
          path: /github/home/.ZAP/reports/
