name: OWASP ZAP Integration with GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          docker_name: 'zaproxy/zap-stable'
          target: 'http://testphp.vulnweb.com/'
          cmd_options: '-config api.disablekey=true'
          
