name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'zaproxy/zap-stable'
          target: 'http://testphp.vulnweb.com/'
          cmd_options: '-config api.disablekey=true'
